<?php

namespace AppBundle\Repository;

/**
 * ConservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConservationRepository extends \Doctrine\ORM\EntityRepository
{
}
