<?php

namespace AppBundle\Repository;

/**
 * DefinitiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefinitiveRepository extends \Doctrine\ORM\EntityRepository
{
}
