<?php

namespace AppBundle\Repository;

/**
 * EpiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpiRepository extends \Doctrine\ORM\EntityRepository
{
}
