<?php

namespace AppBundle\Repository;

/**
 * ProvisoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvisoireRepository extends \Doctrine\ORM\EntityRepository
{
}
