<?php

namespace AppBundle\Repository;

/**
 * RayonnageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RayonnageRepository extends \Doctrine\ORM\EntityRepository
{
}
