<?php

namespace AppBundle\Repository;

/**
 * SortfinalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortfinalRepository extends \Doctrine\ORM\EntityRepository
{
}
