<?php

namespace AppBundle\Repository;

/**
 * SousserieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousserieRepository extends \Doctrine\ORM\EntityRepository
{
}
